{% set name = "oslo.i18n" %}
{% set version = "3.15.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8ec9050bdf840b3d5d0154705804e41625b373fff2bac8ada7d58003e378a71e" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr >=2.0.0

  run:
    - python
    - babel >=2.3.4
    - six >=1.9.0

test:
  imports:
    - oslo_i18n
    - oslo_i18n.log
    - oslo_i18n.fixture

about:
  home: http://docs.openstack.org/developer/oslo.i18n/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Utilities for working with internationalization (i18n) features, especially translation for text strings in an application or library.'
  doc_url: http://docs.openstack.org/developer/oslo.i18n/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.i18n

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
