{% set name = "oslo.i18n" %}
{% set version = "5.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "3484b71e30f75c437523302d1151c291caf4098928269ceec65ce535456e035b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - six >=1.10.0

test:
  imports:
    - oslo_i18n

about:
  home: http://docs.openstack.org/developer/oslo.i18n/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Utilities for working with internationalization (i18n) features, especially translation for text strings in an application or library.
  doc_url: http://docs.openstack.org/developer/oslo.i18n/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.i18n

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
    - tschoonj
