travis:
  secure:
    BINSTAR_TOKEN: OcJAShVYeAWXo2VoTWJVTTki/MIsUytHH8LDF6JvYh7PIQ3F9rQKx+mNtZ6iprbvFWR/xSgIMN6L7ZmStllKKQvvSX1qG0JeJB0Z/6ppAoVO05ck/PaSBjC492HxfVyrg78B14yVpopjwXnFctZaPzxQ4WwJNqCdibWr8Sa4fQtjC6U3SAouIB3r7w3YVTpVypbkYGSF6jj89OSluTUCOk83yvq6YiFyNszi9raEGkjaRmXJATvgVo/guNPA1Ob0g6X+jKJpw67SbmeSHvB5HekhGHow5+WyPay1fhoc7xkUanV0TFu6cy4yc7i0oYou0xFo4jto6/DyKsFxurHJa+N9kmsEpbcyMb+PQAl9IToyTIObJ9wgmKH46Pm5IPP4QEL62YopaWkPVZcmh2eoQToOrlxPH/47d0QSOhl/yc8Kyo30oQFtvBZY4aAMJ0Lz+i3B/FdDQZEZ5BZ+cZpsFGNIcnkYYMZY3gOeKcSCUGqXLcRXR6IrU8B56x9bRbj3CxQ/PJl/mUCxB3TNe8i314vcCdZiW1N1Lh/86wlviPFwi706UmGs8rVVwW7Y2R7WzjiXCmig2ZKVs8RPJOk4ioZheb6MZYbhum5nePyVKIDfSGJiD0/ah8p+SgdMHG/3d3g9SodQCvH1WiUh3hh9ez/Qwk5PPyPKnrGXaNcfyXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
