travis:
  secure:
    BINSTAR_TOKEN: Nq2MVCRteG4iivWee5Zd5rX9JHmvTQ43p7rH1ApQ4ADuIrms+hTaPlO3XpD0tGduZl9v5r3LX3xzaFVUQkdzJs4PqeUK80MCjo+bU+5O2Gob5xRK3jCBkrN2kx5+e6TbCKXgXDOlBtNaLJsW3PNUAGQmtBmR2eeePijYxAiROLOPmc1NtzL3myn5igf++9Yq32ERkdb1aQtQU6FGlynTKsdvSOIHOVp1o3UvIRmgrZoAlliu1ZSuMNhRghbftOjpdT2DoqdKxNmqRGfRqnpIlhPbJMylav1R841yDjkdS2tJYMP8SICME8WWYAjqmOx9kcQAn/GqdG273U2lhQs84lSG44Xmvb+xideITqAdNLODemeGnKPEC75MbrTyVHs/RojI9dj/Se4un3nVLm8cUj7Sms7cV+1GhinOHiFTA0+qcHhubH0ChL9fNSDLzyoz7We2/sqaoZ3UQQ6ntTV7g7CIXILajpOxMciEygqhPICgnKvLplqJI7XuQyhrObOp9hfnOHxs8yTFGXVvzRrLDlmWgs/jNC29aE1Zbx/JHbbuqdN+iExIBjAlkBPP4QHTKQlB/GZcxF/mFPaRWGp/INnxe3jB528IXczVGl3fzn1tBv0KryXILlCVEv0H3I6rZC317DQif+Biur4o2/ZqGSgpYBG0ixEO3Lu5Fy0ep9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
